/* 
 * VGA specifications related definitions
 * 
 * Copyright (c) 2022 arttnba3 <arttnba@gmail.com>
 */

#ifndef GRAPHICS_VGA_H
#define GRAPHICS_VGA_H

/* Text mode */
#define REALMODE_TEXT_MODE_ADDR 0xB8000
#define REALMODE_TEXT_MODE_END  0xB8FFF

#define VGA_TEXT_COLUMNS 80
#define VGA_TEXT_ROWS 25
#define VGA_TEXT_SIZE VGA_TEXT_COLUMNS * VGA_TEXT_ROWS
#define VGA_TEXT_COLOR_BLACK 0x0
#define VGA_TEXT_COLOR_BLUE 0x1
#define VGA_TEXT_COLOR_GREEN 0x2
#define VGA_TEXT_COLOR_CYAN 0x3
#define VGA_TEXT_COLOR_RED 0x4
#define VGA_TEXT_COLOR_MAGENTA 0x5
#define VGA_TEXT_COLOR_BROWN 0x6
#define VGA_TEXT_COLOR_LIGHT_GRAY 0x7
#define VGA_TEXT_COLOR_DARK_GRAY 0x8
#define VGA_TEXT_COLOR_LIGHT_GREEN 0x9
#define VGA_TEXT_COLOR_LIGHT_BLUE 0xA
#define VGA_TEXT_COLOR_LIGHT_CYAN 0xB
#define VGA_TEXT_COLOR_LIGHT_RED 0xC
#define VGA_TEXT_COLOR_PINK 0xD
#define VGA_TEXT_COLOR_YELLOW 0xE
#define VGA_TEXT_COLOR_WHIGHT 0xF

/* VGA Registers */
/**
 * TODO: complete all vga registers
 */
#define CRAPHICS_ADDRESS_REGISTER 0x3CE
#define CRAPHICS_DATA_REGISTER 0x3CE
#define CRTC_ADDRESS_REGISTER 0x3D4
#define CRTC_DATA_REGISTER 0x3D5

/* CRT Controller Data Registers */
#define CRTC_DATA_HORIZONAL_TOTAL 0x0
#define CRTC_DATA_END_HORIZONAL_DISPLAY 0x1
#define CRTC_DATA_START_HORIZONAL_BLANKING 0x2
#define CRTC_DATA_END_HORIZONAL_BLANKING 0x3
#define CRTC_DATA_START_HORIZONAL_RETRACE 0x4
#define CRTC_DATA_END_HORIZONAL_RETRACE 0x5
#define CRTC_DATA_VERTICAL_TOTAL 0x6
#define CRTC_DATA_OVERFLOW 0x7
#define CRTC_DATA_PRESET_ROW_SCAN 0x8
#define CRTC_DATA_MAXIMUN_SCAN_LINE 0x9
#define CRTC_DATA_CURSOR_START 0xA
#define CRTC_DATA_CURSOR_END 0xB
#define CRTC_DATA_START_ADDRESS_HIGH 0xC
#define CRTC_DATA_START_ADDRESS_LOW 0xD
#define CRTC_DATA_CURSOR_LOC_HIGH 0xE
#define CRTC_DATA_CURSOR_LOC_LOW 0xF
#define CRTC_DATA_VERTICAL_RETRACE_START 0x10
#define CRTC_DATA_VERTICAL_RETRACE_END 0x11
#define CRTC_DATA_VERTICAL_DISPLAY_END 0x12
#define CRTC_DATA_OFFSET_REGISTER 0x13
#define CRTC_DATA_UNDERLINE_LOCATION_REGISTER 0x14
#define CRTC_DATA_START_VERTICAL_BLANKING 0x15
#define CRTC_DATA_END_VERTICAL_BLANKING 0x16
#define CRTC_DATA_CRTC_MODE_CONTROL 0x17
#define CRTC_DATA_LINE_COMPARE 0x18

#endif